"""Init

Revision ID: 122ecb47d807
Revises: 
Create Date: 2023-03-23 21:48:56.127197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122ecb47d807'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
