# Generated by Django 4.1.7 on 2023-03-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quoteapp.author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(max_length=4000),
        ),
    ]
